name: Build (Linux)

on: [workflow_dispatch, push, pull_request]

env:
  SFML_DIR: extern/sfml

jobs:
#  lint:
#    name: Clang-format - ENFORCING DISABLED (see #17)!
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: sudo apt install clang-format
#      - name: Run clang-format
#        run: tooling/lint.sh --dry-run
#        # -Werror
  build:
    name: Multi-Build (GCC & CLANG, only on Linux yet!)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [clang++, g++]
        target: [linux]
    steps:
      - uses: actions/checkout@v3
      - name: Install SFML dependencies...
        run: |
          sudo apt install libgl-dev
          # The rest is only needed for static builds:
          sudo apt install libx11-dev
          sudo apt install libxrandr-dev
          sudo apt install libxcursor-dev
          sudo apt install libxi-dev
          sudo apt install libudev-dev
      - name: Download & setup SFML/master...
        run: ./tooling/sfml-setup ${{ matrix.target }}
      - name: Build (Ubuntu only! Windows is being manually tested locally for now...)
        run: make CC=${{ matrix.cc }} TOOLCHAIN=${{ matrix.target }}
